### ISSUE TITLE
预处理的时候就需要读取model？这代码是不是随意改过

### ISSUE THREAD

**Issue by fooSynaptic** [zoulala/Seq2seq_Translation#2]
```
english lines number: 209941
chinese lines number: 209941
字符数量：53380 
Traceback (most recent call last):
  File "read_utils.py", line 178, in <module>
    et = TextConverter(text=a,save_dir='models/en_vocab.pkl', max_vocab=10000, seq_length = 50)
  File "read_utils.py", line 108, in __init__
    with open(save_dir, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/en_vocab.pkl'
```

**Comment by zoulala** [comment]
> english lines number: 209941
> chinese lines number: 209941
> 字符数量：53380 
> Traceback (most recent call last):
>   File "read_utils.py", line 178, in <module>
>     et = TextConverter(text=a,save_dir='models/en_vocab.pkl', max_vocab=10000, seq_length = 50)
>   File "read_utils.py", line 108, in __init__
>     with open(save_dir, 'wb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'models/en_vocab.pkl'

建一个models文件夹就可以
